# This is the correct, simple configuration for your site.
# It tells Netlify where to find your files and functions.
[build]
  command = "echo 'Running build command'"
  publish = "."
  functions = "netlify/functions/"

