[build]
  command = "echo 'Running build command'"
  publish = "."
  functions = "netlify/functions/"

# This section enables Netlify to replace placeholders in your HTML 
# with environment variables during the build.
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true
[build.processing.files]
  "index.html" = { "context" = "production" }

